version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Kolkata"
    groups:
      npm-development-dependencies:
        patterns:
          - "*"
        dependency-type: "development"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Kolkata"
    groups:
      github-actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci"
      include: "scope"
